---
title: "Exposure Category by Gender: Followup Analysis"
author: "Yash Jaggi"
output: 
    bookdown::pdf_document2:
      latex_engine: xelatex
      toc: false
      keep_tex: true
      fig_caption: true
      table_caption: true
header-includes:
  - \usepackage{booktabs}
  - \usepackage{caption}
  - \usepackage{float}
  - \renewcommand{\familydefault}{\sfdefault}
  - \usepackage{placeins}
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(knitr)
library(kableExtra)
library(scales)
library(here)
library(stringr)
library(ggthemes)
library(gtExtras)
library(gtsummary)
library(gt)

knitr::opts_chunk$set(
  dev = "pdf",
  dpi = 300,
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = "90%"
)

data <- read_excel(here("data","snapshots","snapshot.05062024.xlsx"), sheet = "INTOXICATE")

clean_data <- data %>%
  filter(!is.na(Gender), !is.na(`Exposure Category`)) %>%
  mutate(
    Gender = trimws(Gender),
    `Exposure Category` = trimws(`Exposure Category`)
  ) %>%
  filter(Gender %in% c("M", "F")) %>%
  filter(`Exposure Category` %in% c(
    "Combination", "Analgesic", "Antidepressants",
    "Street Drugs", "CO, As, CN", "Sedatives", "Alcohol", "Unknown"
  ))

category_counts <- clean_data %>%
  count(`Exposure Category`) %>%
  arrange(desc(n))

ordered_categories <- category_counts$`Exposure Category`

clean_data <- clean_data %>%
  mutate(`Exposure Category` = factor(`Exposure Category`, levels = ordered_categories))

create_binary_comparison <- function(data, target_category) {
  data %>%
    mutate(category_binary = ifelse(`Exposure Category` == target_category,
      target_category, "All Others"
    ))
}

cont_table <- clean_data %>%
  select(c(`Exposure Category`, Gender)) %>%
   table()

chi_result <- suppressWarnings(chisq.test(cont_table))
chi_p_value <- ifelse(chi_result$p.value < 0.001, "< 0.001",
  format(round(chi_result$p.value, 3), nsmall = 3)
)

overall_significant <- TRUE
significance_text <- ifelse(overall_significant, "significant", "no significant")
```

# Methods {-}
To determine the relationship between gender and the main substance ingested, we stratified exposure counts by gender (Table \ref{tab:gender_by_exposure}). There was no overall systematic difference in exposures between genders.  

```{r gender_by_exposure, results='asis'}
tbl  <-  data  %>%
  filter(Gender != 'NB') %>%
  tbl_cross(row=`Exposure Category`, col=Gender, percent="column") %>%
  add_p()
  
cat("\\begin{table}[H]\\centering\n")
cat(as_kable(tbl, format="latex", booktabs=TRUE))
cat("\\caption{Exposure Category by Gender. Cells show count of cases, percentage of total by gender in parentheses.}\\label{tab:gender_by_exposure}\n")
cat("\\end{table}\n")

```

```{r overall_vs_analgesic}

ad_tbl  <-  data %>%
  filter(Gender != 'NB') %>%
  select(c(`Exposure Category`, Gender)) %>%
  create_binary_comparison("Antidepressants") %>%
  tbl_cross() %>% 
  add_p() %>%
  as_gt()

knitr::asis_output(as_latex(ad_tbl))
  
```

