% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{float}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{placeins}
\usepackage{caption}
\captionsetup[table]{position=bottom}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Linear Independence of Variables in INTOXICATE-ER},
  pdfauthor={Yash Jaggi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Linear Independence of Variables in INTOXICATE-ER}
\author{Yash Jaggi}
\date{}

\begin{document}
\maketitle

\section*{Realtionship Between Gender and Xenobiotic}\label{realtionship-between-gender-and-xenobiotic}
\addcontentsline{toc}{section}{Realtionship Between Gender and Xenobiotic}

\begin{table}[!h]
\centering
\caption{\label{tab:table1}\textbf{No association between gender and type of xenobiotic.}. Cells denote case count (row percentage). F, biological female. M, male. See X for description of exposure categories.}
\centering
\begin{tabular}[t]{lcccccc}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Biological Sex} & \multicolumn{4}{c}{ } \\
\cmidrule(l{3pt}r{3pt}){2-3}
\textbf{} & \textbf{\textit{F}} & \textbf{\textit{M}} & \textbf{Total} & \textbf{p-value} & \textbf{\textbf{Row vs Rest p}} & \textbf{\textbf{Row vs Rest p (adj)}}\\
\midrule
Exposure Category &  &  &  & 0.007 &  & \\
\hspace{1em}\em{Combination} & 25 (42\%) & 34 (58\%) & 59 (100\%) &  & 0.159 & 0.318\\
\hspace{1em}\em{Analgesic} & 19 (59\%) & 13 (41\%) & 32 (100\%) &  & 0.413 & 0.471\\
\hspace{1em}\em{CO, As, CN} & 11 (39\%) & 17 (61\%) & 28 (100\%) &  & 0.257 & 0.411\\
\hspace{1em}\em{Antidepressants} & 22 (76\%) & 7 (24\%) & 29 (100\%) &  & 0.008 & 0.063\\
\addlinespace
\hspace{1em}\em{Unknown} & 15 (54\%) & 13 (46\%) & 28 (100\%) &  & 0.938 & 0.938\\
\hspace{1em}\em{Street Drugs} & 7 (33\%) & 14 (67\%) & 21 (100\%) &  & 0.139 & 0.318\\
\hspace{1em}\em{Alcohol} & 6 (38\%) & 10 (63\%) & 16 (100\%) &  & 0.385 & 0.471\\
\hspace{1em}\em{Sedatives} & 11 (79\%) & 3 (21\%) & 14 (100\%) &  & 0.065 & 0.259\\
Total & 116 (51\%) & 111 (49\%) & 227 (100\%) &  &  & \\
\bottomrule
\multicolumn{7}{l}{\rule{0pt}{1em}\textsuperscript{1} Pearson's Chi-squared test}\\
\end{tabular}
\end{table}

\begin{verbatim}
## 
## Call:
## glm(formula = `Dichotomous Outcome` ~ Gender + Pulse + SBP + 
##     GCS + Age + `Respiratory Insufficiency` + Cirrhosis + `Secondary Reason for ICU Admission` + 
##     Dysrhythmia + `Exposure Category` + Gender * `Exposure Category`, 
##     family = binomial, data = clean_data)
## 
## Coefficients:
##                                              Estimate Std. Error z value Pr(>|z|)   
## (Intercept)                                -1.637e+01  6.523e+03  -0.003  0.99800   
## GenderM                                     8.323e-01  1.027e+00   0.810  0.41782   
## Pulse                                       2.479e-02  1.323e-02   1.873  0.06102 . 
## SBP                                        -9.680e-03  1.060e-02  -0.913  0.36123   
## GCS                                        -3.878e-01  1.357e-01  -2.859  0.00425 **
## Age                                        -6.092e-03  1.241e-02  -0.491  0.62338   
## `Respiratory Insufficiency`No               1.840e+01  6.523e+03   0.003  0.99775   
## `Respiratory Insufficiency`Yes              1.980e+01  6.523e+03   0.003  0.99758   
## CirrhosisYes                                3.895e+00  1.542e+00   2.525  0.01157 * 
## `Secondary Reason for ICU Admission`Yes     1.813e+00  7.590e-01   2.388  0.01692 * 
## DysrhythmiaYes                             -5.307e-01  6.658e-01  -0.797  0.42541   
## `Exposure Category`Analgesic                6.330e-01  1.053e+00   0.601  0.54783   
## `Exposure Category`CO, As, CN              -1.672e-01  1.424e+00  -0.117  0.90654   
## `Exposure Category`Antidepressants         -2.414e+00  2.464e+00  -0.980  0.32714   
## `Exposure Category`Unknown                  4.745e-01  1.110e+00   0.427  0.66902   
## `Exposure Category`Street Drugs            -1.577e+01  2.418e+03  -0.007  0.99480   
## `Exposure Category`Alcohol                 -3.878e-01  2.028e+00  -0.191  0.84833   
## `Exposure Category`Sedatives                1.206e-01  1.380e+00   0.087  0.93035   
## GenderM:`Exposure Category`Analgesic        1.053e+00  1.412e+00   0.746  0.45591   
## GenderM:`Exposure Category`CO, As, CN       8.452e-01  1.600e+00   0.528  0.59734   
## GenderM:`Exposure Category`Antidepressants -1.503e+01  2.169e+03  -0.007  0.99447   
## GenderM:`Exposure Category`Unknown         -3.362e-01  1.513e+00  -0.222  0.82421   
## GenderM:`Exposure Category`Street Drugs     1.565e+01  2.418e+03   0.006  0.99484   
## GenderM:`Exposure Category`Alcohol          5.844e-01  2.278e+00   0.257  0.79749   
## GenderM:`Exposure Category`Sedatives       -1.703e+01  4.583e+03  -0.004  0.99704   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 208.22  on 218  degrees of freedom
## Residual deviance: 130.82  on 194  degrees of freedom
##   (8 observations deleted due to missingness)
## AIC: 180.82
## 
## Number of Fisher Scoring iterations: 17
\end{verbatim}

\begin{verbatim}
## 
## Call:
## glm(formula = `Dichotomous Outcome` ~ Pulse + SBP + GCS + Age + 
##     `Respiratory Insufficiency` + Cirrhosis + `Secondary Reason for ICU Admission` + 
##     Dysrhythmia + `Exposure Category`, family = binomial, data = clean_data)
## 
## Coefficients:
##                                           Estimate Std. Error z value Pr(>|z|)   
## (Intercept)                             -1.178e+01  1.455e+03  -0.008  0.99354   
## Pulse                                    2.125e-02  1.221e-02   1.741  0.08170 . 
## SBP                                     -6.656e-03  1.017e-02  -0.654  0.51287   
## GCS                                     -3.963e-01  1.296e-01  -3.059  0.00222 **
## Age                                     -4.742e-03  1.202e-02  -0.394  0.69326   
## `Respiratory Insufficiency`No            1.425e+01  1.455e+03   0.010  0.99219   
## `Respiratory Insufficiency`Yes           1.551e+01  1.455e+03   0.011  0.99149   
## CirrhosisYes                             3.508e+00  1.400e+00   2.506  0.01221 * 
## `Secondary Reason for ICU Admission`Yes  1.938e+00  7.174e-01   2.701  0.00691 **
## DysrhythmiaYes                          -3.998e-01  6.315e-01  -0.633  0.52669   
## `Exposure Category`Analgesic             1.006e+00  6.957e-01   1.447  0.14803   
## `Exposure Category`CO, As, CN            5.372e-01  8.046e-01   0.668  0.50435   
## `Exposure Category`Antidepressants      -3.142e+00  2.130e+00  -1.475  0.14015   
## `Exposure Category`Unknown               3.001e-01  7.538e-01   0.398  0.69050   
## `Exposure Category`Street Drugs         -9.107e-02  9.549e-01  -0.095  0.92402   
## `Exposure Category`Alcohol               2.312e-01  9.499e-01   0.243  0.80769   
## `Exposure Category`Sedatives            -4.864e-01  1.214e+00  -0.401  0.68861   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 208.22  on 218  degrees of freedom
## Residual deviance: 140.08  on 202  degrees of freedom
##   (8 observations deleted due to missingness)
## AIC: 174.08
## 
## Number of Fisher Scoring iterations: 14
\end{verbatim}

\begin{verbatim}
## # A tibble: 2 x 2
##      TP    TN
##   <int> <int>
## 1   163    37
## 2     0    23
\end{verbatim}

\begin{verbatim}
## # A tibble: 2 x 2
##      TP    TN
##   <int> <int>
## 1   163    37
## 2     0    23
\end{verbatim}

There was no overall association between gender and exposure category (p=0.007, Table \ref{tab:table1}) even though most exposures to antidepressant and analgesic exposures involved females, 22 (76\%) and 19 (59\%), respectively and most exposures to CO/As/CN and street drugs involved males, 17 (61\%) and 14 (67\%), respectively. There was no significant association between gender and any type of exposure.

Including gender in a regression model changed the Aikake Information Criteria (AIC) from 174.08 to 180.82, a minimal difference. Substituting gender for exposure category changed the AIC to 165.35, also a minimal difference. These results suggest thats gender and exposure category provide overlapping information. Omitting both variables changed the AIC 169.89, suggesting that neither variable adds predictive value in this data set.

\section*{TODO}\label{todo}
\addcontentsline{toc}{section}{TODO}

\begin{itemize}
\tightlist
\item
  Compare Distribution of INTOXIICATE Scores with and without Exposure Category
\item
  kk
\end{itemize}

\section*{Heart Rate and Dysrhythmia}\label{heart-rate-and-dysrhythmia}
\addcontentsline{toc}{section}{Heart Rate and Dysrhythmia}

\begin{table}[t]
\fontsize{12.0pt}{14.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lcccc}
\toprule
 & \multicolumn{2}{c}{\textbf{Dysrhythmia}} &  &  \\ 
\cmidrule(lr){2-3}
 & No & Yes & \textbf{Total} & \textbf{p-value}\textsuperscript{\textit{1}} \\ 
\midrule\addlinespace[2.5pt]
{\bfseries HR faster than 100 bpm} &  &  &  & <0.001 \\ 
    No & 143 (93\%) & 10 (6.5\%) & 153 (100\%) &  \\ 
    Yes & 31 (44\%) & 39 (56\%) & 70 (100\%) &  \\ 
{\bfseries Total} & 174 (78\%) & 49 (22\%) & 223 (100\%) &  \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\textsuperscript{\textit{1}}Pearson's Chi-squared test\\
\end{minipage}
\end{table}

Heart rate, a continuous variable, and the presence of a dysrhythmia, a dichotomous variable, may not be independent variables in the model in Brandenberg et al.~(2020). That model did not specify whether to classify sinus tachycardia as a dysrhythmia. It is considered a dysrhythmia and the most common dysrhthmia in in stimulant toxicity. We found a significant association between a heart rate faster than 100 bpm and the presence of dysrhythmia (p\textless0.001). Seventy patients had a heart rate faster than 100 bpm, of whom 39 (56\%) were coded as having a dysrhythmia.

A model including heart rate and the indicator variable for dysrhythmia had an Aikaike Information Criterion (AIC) of 20, compared to 18 for a model without the indicator variable. These results suggests that the indicator variable has no additional predictive value for this model in this data set. In the model of Brandenburg et al.~(2020), the presence of dysrhythmia on its own raises the IRS by 6 points, the threshold for ICU admission. If the variable has no predictive value beyond heart rate, this could decrease the specificity of the model.

\section{Summary and Conclusions}\label{summary-and-conclusions}

\subsection{Gender Analysis}\label{gender-analysis}

The chi-square test showed a significant association between gender and exposure category . After applying Bonferroni correction for three focused comparisons, the Antidepressants vs All Others comparison remained significant, demonstrating a robust gender difference that withstands conservative adjustment for multiple testing.

Key patterns identified:
- Females more likely to present with antidepressant and analgesic exposures
- Males more likely to present with CO/As/CN, street drugs, and alcohol exposures
- These patterns reflect true population associations rather than sampling variation

\subsection{Regression Findings}\label{regression-findings}

\textbf{1. Dysrhythmia-Heart Rate Relationship (Analysis 1):} Heart rate significantly predicts dysrhythmia (\emph{p} \textless{} 0.001), with patients exhibiting dysrhythmia having substantially higher mean heart rates (112.7 vs 86.0 bpm). This strong relationship raises questions about potential collinearity and whether dysrhythmia is simply a recoding of heart rate.

\textbf{2. Dysrhythmia Variable (Analysis 2):} Despite strong correlation with heart rate, dysrhythmia provides independent predictive value for Actual Disposition (\emph{p} = 0.024). This suggests dysrhythmia captures additional clinical information beyond heart rate alone---potentially reflecting rhythm abnormalities at various rates or serving as a marker for specific poison types. However, the original INTOXICATE study noted collinearity between dysrhythmia and pulse, and our Analysis 1 confirms this relationship. The question remains whether dysrhythmia should be weighted differently in ED versus ICU populations.

\textbf{3. Gender as Latent Variable:} While not formally tested in regression analyses here, the gender-exposure category associations from Table 1 demonstrate that gender acts as a latent variable in toxicology presentations. Gender predicts exposure type (males → street drugs/CO/As/CN, females → antidepressants/analgesics), but prior research has shown it does not independently predict ICU disposition when clinical severity markers are included. This supports the original INTOXICATE model's exclusion of gender as a direct predictor.

\subsection{Clinical Implications}\label{clinical-implications}

The original INTOXICATE model was developed in ICU patients and may require calibration for ED application. Our findings suggest:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Gender as Latent Variable:} Gender predicts Exposure Category patterns (as shown in Table 1) but does not appear to independently predict Actual Disposition once clinical severity is accounted for. Males more commonly present with street drugs and CO/As/CN exposures; females more commonly with antidepressants and analgesics. However, based on the literature and clinical experience, the clinical presentation (vital signs, mental status, organ dysfunction) is what predicts ICU admission, regardless of gender. This supports the original model's decision to exclude gender.
\item
  \textbf{Rate vs Rhythm Debate:} While dysrhythmia is highly dependent on heart rate per Analysis 1, it retains independent predictive value per Analysis 2. Clinically, \textbf{rate is far more important than rhythm} in toxicology. The key question is whether a wide complex tachycardia at 200 bpm is meaningfully different from a narrow complex tachycardia at 200 bpm for predicting ICU disposition. The original INTOXICATE model gave substantial weight to dysrhythmia, which may be appropriate for ICU patients but potentially excessive for ED populations. Future work should explore whether dysrhythmia acts as a marker for specific poison types.
\item
  \textbf{Population-Specific Calibration:} The relationship between variables may differ between ICU (where INTOXICATE was developed) and ED populations (our validation cohort). Rather than adding/removing variables, model performance in ED may benefit from:

  \begin{itemize}
  \tightlist
  \item
    Threshold adjustment (changing the bias/constant term: y = mx + b)
  \item
    Coefficient reweighting (especially for dysrhythmia)
  \item
    Understanding why the model underperforms in ED versus ICU
  \end{itemize}
\item
  \textbf{Risk Stratification Considerations:} The tradeoff between undercalling (missing ICU admissions) and overcalling (unnecessary ICU admissions) may differ between settings. Future ROC analysis should identify optimal thresholds for ED populations.
\end{enumerate}

\subsection{Study Limitations}\label{study-limitations}

\begin{itemize}
\tightlist
\item
  Small sample size (n = ) for regression analyses) limits statistical power
\item
  Limited to toxicology consultations rather than all ED presentations - biased toward patients sick enough to warrant specialist consultation
\item
  Binary gender classification does not capture full spectrum of gender identity
\item
  Cross-sectional design limits causal inference
\item
  Single-center study may limit generalizability to other ED populations
\item
  Dataset structure differs from original INTOXICATE (lacks Temperature, QRS, QTc measurements)
\item
  Time series considerations not addressed (e.g., which pulse measurement to use)
\item
  Population skewed toward younger patients with intentional self-harm (suicide attempts)
\end{itemize}

\subsection{Conclusion}\label{conclusion}

This analysis demonstrates that gender is significantly associated with Exposure Category patterns in toxicology consultations (Table 1), with the antidepressants association remaining significant even after Bonferroni correction. While we did not formally test gender's effect on ICU disposition in regression models here, these exposure pattern differences suggest gender acts as a \textbf{latent variable} - males and females present with different poison exposures, but based on clinical understanding, it is the clinical severity markers (not gender itself) that determine ICU admission.

Dysrhythmia, despite strong correlation with heart rate (Analysis 1), retains independent predictive value for ICU disposition (Analysis 2, \emph{p} = 0.024) and should remain in the model. However, the original INTOXICATE model noted collinearity between these variables, and clinically \textbf{rate is far more important than rhythm}. The question of whether dysrhythmia should be weighted differently in ED versus ICU populations warrants investigation.

These findings support the original INTOXICATE model structure while highlighting the need for \textbf{population-specific calibration} when applying ICU-derived models to ED populations. The model underperforms in ED compared to ICU - understanding why requires examining threshold adjustment and coefficient reweighting rather than variable addition/removal. Future work should focus on:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ROC analysis to quantify the impact of dysrhythmia and identify optimal thresholds
\item
  Threshold optimization for ED populations (adjusting bias term)
\item
  Investigating whether dysrhythmia serves as a marker for specific poison types
\item
  External validation to confirm these findings
\end{enumerate}

The ultimate goal is not to rebuild the model, but to recalibrate it for ED use through threshold adjustment (y = mx + b, optimize b) and possibly coefficient reweighting (optimize m for dysrhythmia). This approach maintains the model's validated structure while adapting it to the different risk profile of ED versus ICU toxicology patients.

\end{document}
